logo:
  nav_mobile: images/logo-apollo-space-left.svg
  subbrand: images/logo-apollo-subbrands-developers-space.svg
  title: Apollo
  subtitle: Developers
  url: https://www.apollographql.com/
favicon: images/favicon.png
